### ISSUE TITLE
Should config FW_PACKAGE_REPLACES translate to RPM's obsoletes?

### ISSUE THREAD

**Issue by dhull** [dukesoferl/fw#5]
Framewerk supports a FW_PACKAGE_REPLACES variable that corresponds to the .deb format's "Replaces" field. Perhaps for .rpm this should correspond to the "obsoletes" field.

**Comment by djnym** [comment]
Yeah, it probably should.  Any idea where it goes now?  May not go anywhere, but I swear I've used it.

**Comment by djnym** [comment]
This was done in PR https://github.com/dukesoferl/fw/pull/16
